PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
MaxAuthTries 3
AllowUsers ubuntu
X11Forwarding no
AllowTcpForwarding no
PermitEmptyPasswords no
